### ISSUE TITLE
missing `dryRun` equivalent?

### ISSUE THREAD

**Issue by josepot** [paritytech/json-rpc-interface-spec#55]
The "legacy" JSON-RPC API has [a `dryRun` method](https://polkadot.js.org/docs/substrate/rpc/#dryrunextrinsic-bytes-at-blockhash-applyextrinsicresult), which can be very helpful in order to prevent users from spending funds on transactions that are doomed to fail.

I'm aware that `transaction_unstable_submitAndWatch` emits a `validated` event which indicates that the transaction is considered valid. However, unless I misunderstood something, a valid transaction can fail to execute, thus causing the user to waste funds on that transaction.

A `dryRun` can (in most cases) prevent this from happening. So, I think that it would be a good idea to have a way to support this functionality.

cc: @tomaka

**Comment by tomaka** [comment]
This can be replaced with `chainHead_unstable_call` with function name `TaggedTransactionQueue_validate_transaction` and parameters `concat(2, transaction_bytes, block_hash)`

**Comment by josepot** [comment]
> This can be replaced with `chainHead_unstable_call` with function name `TaggedTransactionQueue_validate_transaction` and parameters `concat(2, transaction_bytes, block_hash)`
> 
> The block hash has to be the same as the one you call the function against, it's a wart in the Substrate code.

Awesome! Thanks @tomaka !

**Comment by tomaka** [comment]
However I want to clarify

> However, unless I misunderstood something, a valid transaction can fail to execute, thus causing the user to waste funds on that transaction.

Transaction do not have fees. Some specific transactions, such as balance transfers, have fees. Fees are not a property of a transaction, but are part of the logic of specific transactions.
So if a transaction fails, fees aren't be consumed, because consuming the fees would require the transaction to succeed. There's never a world where fees are consumed but the rest of the transaction isn't applied.

A valid transaction can fail only if a conflicting transaction was submitted at the same time. For example if you have an account with 3 DOTs and you send two transfers of 2 DOTs from two different machines, one transaction will fail.

**Comment by josepot** [comment]
> For this reason I really doubt the utility of system_dryRun.

Coming from Ethereum, I was surprised to see that in Substrate, a transaction can still get into the blockchain even if it throws errors. My understanding is that In Ethereum, if a transaction triggers errors, it doesn't get added to the chain, though you still pay the fees.

So in Substrate, users can end up paying for what they see as 'failed' transactions, even though technically they made it into a block. That's why I think having a 'dry run' feature would be super helpful. It'd give folks a heads-up about potential issues before the transaction is set in stone on the chain. That way, we could avoid users wasting money on transactions that don't do what they expect.

**Comment by tomaka** [comment]
The current `system_dryRun` is implemented as a call to `BlockBuilder_apply_extrinsic`, and returns whether the transaction would be an error.
