### ISSUE TITLE
`chainHead_unstable_storage` needs a limit to the number of items

### ISSUE THREAD

**Issue by tomaka** [paritytech/json-rpc-interface-spec#58]
cc https://github.com/paritytech/json-rpc-interface-spec/pull/51

I now remember why prior to https://github.com/paritytech/json-rpc-interface-spec/pull/51 each call to `chainHead_unstable_storage` could only subscribe to one item.
The reason is that we need a limit to the number of items you can subscribed to at any given time, as otherwise an attacker could subscribe to millions of keys.

**Comment by josepot** [comment]
Good point!

I can think of 2 feasible solutions:

1) The return value of `chainHead_unstable_storage` is a documented error that lets the client know that the subscription limit has been exceeded (rather than returning an opaque value representing the operation).
2) Add a new notification like `subscription-limit-exceeded`, which -if it occurs- then it should be the first and only notification that would be produced.

Both options would allow the client to gracefully handle this situation by retrying with less items and/or waiting for some subscriptions to resolve before retrying.

Personally, I would go with the first option.

What I don't quite understand is: why does allowing the query of multiple items at the same time create this issue? Wouldn't this same issue also exist prior to that change? If the client had made several requests in parallel, then there should be an spec documented way to let the client know that they have reached the limit of subscriptions. So, that the client can gracefully handle that scenario (irregardless of whether multiple queries at the same time are allowed or not).

Maybe what makes it different is that before a generic documented error would have sufficed, while now it could also be useful if the error (or notification) provided the number of empty slots available for new subscriptions? 🤔

**Comment by tomaka** [comment]
> I can think of 2 feasible solutions:

The problem is not how the server checks the limit or how it reports that the limit has been exceeded, but what the client can expect to work.

If the server can return an error at any point, and the client encounters this error, what is it supposed to do? Stop and print an error? That'd be an extremely bad UX. You want to guarantee that the code in your client will not trigger said limit.

> Wouldn't this same issue also exist prior to that change?

There exists a limit to the total number of subscriptions. If one item equals one subscription, the number of items is also automatically limited.

**Comment by josepot** [comment]
My perspective is this: it's essential to establish appropriate boundaries for this specification. Rather than attempting to predict all potential use cases of the API, the specification should offer a well-documented method for consumers to determine their responses to given situations.

In essence, the crux of the issue lies in how the scenario is communicated to the consumer. I think that we need a well documented response that offers adequate context for consumers to decide how to navigate this scenario.

**Comment by tomaka** [comment]
As I've said, it's not that easy.
Let's say that the JSON-RPC client asks for 10 items, and the server sends back an error "limit exceeded". As the client, what do you next? Do you try with 5, and then send the other 5 later? And if there's still an error when you ask for 5, you try with 2? Then 1? Then 0? That would be a pretty stupid API.

A better way would be to have the limit set in advance, so that the JSON-RPC client can self-enforce it. However, having a precise limit known in advance is pretty hard because it depends on the storage items that you request.
If 5000 JSON-RPC clients all request 20 times the runtime code at the same time, that's going to use 200 GiB of memory to reserve on the server, which will likely crash it. If 5000 JSON-RPC clients all request 20 account balances, that's only 800 kiB of memory to reserve, which is very little.

**Comment by josepot** [comment]
> As I've said, it's not that easy. Let's say that the JSON-RPC client asks for 10 items, and the server sends back an error "limit exceeded". As the client, what do you next? Do you try with 5, and then send the other 5 later? And if there's still an error when you ask for 5, you try with 2? Then 1? Then 0? That would be a pretty stupid API.

I mean... Stupid or not... That is good enough for me! 😅 For sure!

In a situation where a request doesn't go through, my approach would be to halve the items and retry. If it succeeds, I might split the successful items and create a new request, while simultaneously checking for resolved requests. Using the information from resolved requests, I could estimate how many slots are available and adjust my strategy accordingly.

However, different libraries might opt for different trade-offs. Some might wait for ongoing requests to finish before retrying with a different request volume. The key point I want to highlight is that it's entirely feasible for library developers to design a public API that effectively hides these implementation details from end consumers, ensuring requests are resolved even when they initially exceed limits, without the user ever being aware of it.

**Comment by tomaka** [comment]
Additionally:

- Remove `networkConfig` completely.
- Treat [chainHead_unstable_call](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_call.html#chainhead_unstable_call) and [chainHead_unstable_body](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_body.html#chainhead_unstable_body) the same way. They could refuse to start if there are too many items in the queue. Each call to `call` or `body` would occupy "1 slot" when it comes to the 16 slots.

`call` and `body` would use the same server-side FIFO queue.

**Comment by josepot** [comment]
I completely agree with the solution that @tomaka is proposing. Thanks @tomaka!
