### ISSUE TITLE
`chainHead_follow`: allow optional resuming from given block hash

### ISSUE THREAD

**Issue by jsdw** [paritytech/json-rpc-interface-spec#81]
The problem I am thinking about here is this: If I call `chainHead_follow` and would like to take some action for eg each finalized block (eg checking it for a transaction, or checking whether some storage path has changed), what do I do in the event of a (possibly brief) network failure? Right now, my only choice is to subscribe to `chainHead_follow` again. In this case, perhaps I've missed some crucial finalized blocks, eg the block that the transaction made it into or whatever it is I'm interested in.

It would be nice if it were possible to at least attempt to pick up from where I left off. I acknowledge that for various reasons, (eg the server no longer knowing about blocks produced since the disconnection) this might not succeed, but I wonder whether in reality, it often would succeed.

I'm aware that I can use the `archive` methods to get "older" blocks, but this of course won't work if I'm talking to a light client, and more generally it means relying on a new group of functions. My main use case is fetching blocks that are probably pretty recent (produced in the last couple of minutes), so I wonder whether there's scope for the `chainHead` functions to help out here.

One possible option is to achieve this is to add an optional `hash` parameter to `chainHead_follow`. 
- If `hash` is `null` or not provided, then the call works as it does right now.
- If `hash` corresponds to a block that the server no longer knows about, or any descendents of that block are not known to the server, then an error is returned (I'd expect that a client would then acknowledge that it can't pick up from where it left off, possibly report this fact to the user, and subscribe again with no `hash`).
- If `hash` correpsonds to a known block (maybe it has to be a finalized block), and all of the relevant descendents that we'd want to report are also known about still, then we return a list of `finalized` blocks produced since this hash via the usual event to catch us up to present, pin them, and then continue on as we would normally have done without a `hash` parameter.

All in all, I'm open to any thoughts and ideas here! @josepot is this something that you've considered already, and maybe already have thoughts on how to address? @tomaka, does this sort of use case make sense to support at all?

**Comment by josepot** [comment]
> @josepot is this something that you've considered already, and maybe already have thoughts on how to address? 

Absolutely, I've given considerable thought to the matter at hand. I've been delving deep into building decentralized applications on top of substrate networks, and I think it might be beneficial if I write down these thoughts. Sharing this would provide a clearer picture of the perspective I'm coming from. Though I'm currently on vacation, my intent is to articulate these thoughts soon, so please bear with me.

However, just to give a hint: the approach you're suggesting doesn't completely resonate with me, at least in its current form. If we were to incorporate a similar functionality, I'd lean more towards an API named `chaiHead_unstable_pinAncestors` (or something similar). This would ideally accept two arguments: `from` (referring to a non-pinned block's hash ancestor) and `to` (indicating a currently pinned block's hash). The response could be `null` or an error if the request can't be fulfilled. On the other hand, if the server locates the blocks, it'd return an ordered array of newly pinned blocks, starting with the `from` hash and ending with the `to` block, also capturing the intervening blocks now pinned.

Moreover, while the proposed API seems appealing, it's essential to remember that a well-designed decentralized app should always be prepared to handle scenarios where some finalized blocks might be missed. I'll delve deeper into this in my upcoming write-up. 🙂

**Comment by tomaka** [comment]
> what do I do in the event of a (possibly brief) network failure? Right now, my only choice is to subscribe to chainHead_follow again

A network failure does **not** by itself cause the  ̀chainHead_follow` to generate a `stop` event.
Of course, it will stop generating events, but as soon as the network is back again the events will resume.

A `stop` event is generated when the client would have to store too many blocks in its memory. If the client loses connectivity for example for an entire hour, and that the network comes back again, the client will receive 600 blocks all at once, which is too much for it, and it will then generate a `stop` event.

The reason why a `stop` event is generated is that the client wants to throw away the blocks at which it is.

> It would be nice if it were possible to at least attempt to pick up from where I left off.

...consequently, this will always fail.

If you ask for the block where you were before the `stop`, the server will always say that it doesn't have it anymore, because if it still had it then it wouldn't have generated a `stop` in the first place.

**Comment by jsdw** [comment]
> A network failure does not by itself cause the chainHead_follow to generate a stop event.
Of course, it will stop generating events, but as soon as the network is back again the events will resume.

I had thought that most WebSocket implementations connecting to the RPC APIs would timeout and disconnect in case of a network interruption of 30-60 seconds (eg because they send PINGs and don't get PONGs back, or some underlying tcp stream timeout)? And proxies that may be sitting between them like nginx I think has 60sec default timeouts. So while in theory it could live forever, I wonder how often it would in reality.

> If we were to incorporate a similar functionality, I'd lean more towards an API named chaiHead_unstable_pinAncestors (or something similar).

I also thought about an API like that; I'm open to any ideas really if it ultimately makes sense!

> Moreover, while the proposed API seems appealing, it's essential to remember that a well-designed decentralized app should always be prepared to handle scenarios where some finalized blocks might be missed.

Yup; it would, at best, help in some cases but certainly not all!

I guess if you miss this information, a fallback to know whether a tx "went through" via a light client is to rely on transaciton mortality to know when it expires, and check the state for whatever change you expect.

> I'll delve deeper into this in my upcoming write-up. 

..but anyway, it'll be good to hear your throughts on these things in more detail then once you're back; I'd like to get a better feeling for the sorts of patterns that people can leverage (and it's the sort of thing I could then also nudge Subxt users towards). For now, enjoy your holiday!

**Comment by tomaka** [comment]
Ah you were talking about a networking issue between the JSON-RPC client and server, while I assumed you were talking about a networking issue between the JSON-RPC server and the rest of the peer-to-peer network.

I understand the reasoning, but I'm tempted to go with "this isn't supposed to happen anyway". It obviously can't happen in the case of an embedded light client, and in the case of a remote JSON-RPC server it should only ever happen if the server crashes or does some kind of maintenance.

In case of a load balancer (I'm generally assuming that most remote JSON-RPC servers are behind a load balancer), it might be that the JSON-RPC client was connected to server A, then disconnects, then reconnects and gets routed to server B, which doesn't have the block.

**Comment by jsdw** [comment]
> I understand the reasoning, but I'm tempted to go with "this isn't supposed to happen anyway". 

One case is a load balancer scenario where we call `"stop"` on a load of connections to balance them to a new node that's been started (this just came up in a chat and so I was reminded of this case :)).

I am still wondering how best to handle the case we can run into right now where we miss a finalized block (or two) between `"stop"` being called and starting a new subscription.

If I submit a transaction and then "stop" is called and the `chainHead_follow` restarts, I may no longer be able to find that transaction in any block I'm told about. Or perhaps I'm just trying to monitor and log some details for all of the new finalized blocks on some chain, and the "stop" causes me to miss one.

In practise, I suspect that the new node I connect to will have (or could have, quite easily?) the missing finalized block(s) in memory because they are recent, so 99% of the time, if I were able to resume from some finalized block hash, I could pick up from where I left off with 0 interruptions. This allows for nicer UX I think. 

> It obviously can't happen in the case of an embedded light client

I do see the point that when talking to a light client, you should never really see a "stop" though (unless you forget to unpin blocks quickly enough, but that's what I raised https://github.com/paritytech/json-rpc-interface-spec/issues/109 for)

**Comment by tomaka** [comment]
> If I submit a transaction and then "stop" is called and the chainHead_follow restarts, I may no longer be able to find that transaction in any block I'm told about.

This is the exact same situation as a `Dropped` event in the legacy JSON-RPC API.

Yes you won't be able to know whether the transaction is in a block, but it's fundamentally not possible to guarantee you being able to know whether a transaction is in a block, no matter what the JSON-RPC API.

In the way the Substrate/Polkadot blockchain is currently designed, it is fundamentally not possible to avoid missing blocks.
This is not a defect in the JSON-RPC API. The JSON-RPC API simply reflects that reality.

**Comment by tomaka** [comment]
Rather than the client specifying a block hash, I think that a better idea would be for the server to initialize the subscription with a few finalized blocks already pinned.

**Comment by tomaka** [comment]
There are basically two "normal" situations where you'd get a `stop` event: if the JSON-RPC server does a warp sync, or in the example of a load balancer. In the first situation, there's not much you can do and you will miss blocks.

When it comes to the load balancer example, in principle the non-finalized blocks are normally enough in order to not miss a block.
In other words, if you get a `stop` event and immediately resubscribe, you will 99.9% of the time get a finalized block that is either the finalized block of the previous subscription, or one of the non-finalized blocks.

The main problem with doing that is that it would force the JSON-RPC client to examine all forks. For example, if you're searching for a transaction, you would have to download the body of every non-finalized block, and not just of the best block. One counter-point is Sassafras would completely eliminate forks under normal conditions.

The other problem with doing that is that it implicitly relies on the fact that there are typically 3 blocks between the finalized block and the head of the chain. If a chain was configured to immediately finalize blocks (which is totally possible, the reason why there's a gap of 3 blocks is in order to be able to save a chain if it gets stuck without having to revert finality), then you could miss blocks even when resubscribing immediately.

With all that taken into account, I think that an alternative idea would be for the JSON-RPC server to initialize subscriptions with a few finalized blocks already pinned. In other words, the `initialized` event would contain for example the last 8 finalized blocks, and they are all pinned.

**Comment by josepot** [comment]
> I think that an alternative idea would be for the JSON-RPC server to initialize subscriptions with a few finalized blocks already pinned. In other words, the initialized event would contain for example the last 8 finalized blocks, and they are all pinned.

I'm 100% on board with this.

**Comment by jsdw** [comment]
Likewise; that sounds like a great solution to me! Thankyou for the detailed response @tomaka!
