### ISSUE TITLE
`transaction_submitAndWatch`: consider returning "index" as integer, not string

### ISSUE THREAD

**Issue by jsdw** [paritytech/json-rpc-interface-spec#83]
Just a small thing for consideration; events like "finalized" look like:

```
{
    "event": "finalized",
    "block": {
        "hash": "0x...",
        "index": "2"
    }
}
``` 

The "index" is a string, not a number. Given that we never expect indexes to be particularly huge (certainly not outside what JS can interpret as a number), should we just return the integer instead?

Consistency is a reason for doing so, eg with this event on the same subscription, `numPeers` is an integer, not a string:

```
{
    "event": "broadcasted",
    "numPeers": ...
}
```

What's your preference?

**Comment by josepot** [comment]
I completely agree that it makes total sense for the value of this JSON field to be a number, rather than a sting. Absolutely! 

> certainly not outside what JS can interpret as a number

However, I would like to clarify that in some cases it could be useful to pass numbers that can potentially be very large as strings, so that in JS we can use `BigInt` to parse those large numbers. For instance, we could use this custom `JSON.parse`:

```ts
const bigIntJsonParse = (input: string) =>
  JSON.parse(input, (_, value) =>
    !isNaN(value) && !Number.isSafeInteger(+value) ? BigInt(value) : value,
  )
```

I've actually used this in the past 🙂 

This would be completely unnecessary in this case, of course. I just wanted to clarify that since BigInts were introduced into the ECMAScript spec, it's now possible for JS to handle large numbers, even when they are passed through JSON values.
