### ISSUE TITLE
Do we need to specify merkle value for `closestDescendantMerkleValue`?

### ISSUE THREAD

**Issue by bkchr** [paritytech/json-rpc-interface-spec#88]
Reading the spec it isn't clear to me if merkle value returned by `closestDescendantMerkleValue` is an opaque object or we need to specify it? I mean it probably makes 100% sense to keep it opaque, but then we should mention this and also mention that this can not be compared across different implementations (not sure someone would ever do this).

**Comment by tomaka** [comment]
The "Merkle value" is what is defined in the spec: https://spec.polkadot.network/chap-state#sect-merkl-proof

It's either the node value if it's `< 32 bytes` or the hash of the node value if it's `>= 32 bytes`.
(and the node value is `concat(header, partial key, children bitmap, storage value, children)`)

Saying that the value is opaque instead of well-defined means that the value might change after `chainHead_follow` generates a `stop` event, which actually complicates the JSON-RPC-client-side code (maybe quite a lot) as it must make sure to clear all its caches.

**Comment by bkchr** [comment]
I'm also in for making it non opaque. That was the main reason I created this issue, to get consensus on this.

**Comment by bkchr** [comment]
But then we should still specify it. I would assume return an encoded version of a SCALE encoded enum like this:
```
enum MerkleValue {
     Node(Vec<u8>),
     Hash(H),
}
```

Does that makes sense to you?

**Comment by tomaka** [comment]
The Merkle value is:

- Equal to the node value if the node value is < 32 bytes
- Equal to the hash of the node value otherwise

I don't see what more to specify
